
# Gem::Specification for Libxml_rails-0.0.2
# Originally generated by Echoe

--- !ruby/object:Gem::Specification 
name: libxml_rails
version: !ruby/object:Gem::Version 
  version: 0.0.2
platform: ruby
authors: 
- Brandon Mitchell
autorequire: 
bindir: bin

date: 2008-07-29 00:00:00 -07:00
default_executable: 
dependencies: 
- !ruby/object:Gem::Dependency 
  name: activesupport
  type: :runtime
  version_requirement: 
  version_requirements: !ruby/object:Gem::Requirement 
    requirements: 
    - - ">="
      - !ruby/object:Gem::Version 
        version: "0"
    - - "="
      - !ruby/object:Gem::Version 
        version: 2.1.0
    version: 
- !ruby/object:Gem::Dependency 
  name: libxml-ruby
  type: :runtime
  version_requirement: 
  version_requirements: !ruby/object:Gem::Requirement 
    requirements: 
    - - ">="
      - !ruby/object:Gem::Version 
        version: 0.8.3
    version: 
- !ruby/object:Gem::Dependency 
  name: echoe
  type: :development
  version_requirement: 
  version_requirements: !ruby/object:Gem::Requirement 
    requirements: 
    - - ">="
      - !ruby/object:Gem::Version 
        version: "0"
    version: 
description: A plugin substituting libxml-ruby for XmlSimple in Rails.
email: brandon (at) systemisdown (dot) net
executables: []

extensions: []

extra_rdoc_files: 
- lib/bitbckt/core_ext/hash/conversions.rb
- README
- libxml_rails.gemspec
files: 
- init.rb
- lib/bitbckt/core_ext/hash/conversions.rb
- Manifest
- MIT-LICENSE
- Rakefile
- README
- libxml_rails.gemspec
has_rdoc: true
homepage: http://github.com/bitbckt/libxml_rails
post_install_message: 
rdoc_options: 
- --line-numbers
- --inline-source
- --title
- Libxml_rails
- --main
- README
require_paths: 
- lib
required_ruby_version: !ruby/object:Gem::Requirement 
  requirements: 
  - - ">="
    - !ruby/object:Gem::Version 
      version: "0"
  version: 
required_rubygems_version: !ruby/object:Gem::Requirement 
  requirements: 
  - - "="
    - !ruby/object:Gem::Version 
      version: "1.2"
  version: 
requirements: []

rubyforge_project: libxml_rails
rubygems_version: 1.2.0
specification_version: 2
summary: A plugin substituting libxml-ruby for XmlSimple in Rails.
test_files: []
